[package]
name = "roboclaw_python"
version = "0.6.0"
edition = "2021"

[lib]
name = "roboclaw_python"
crate-type = ["cdylib"]

[dependencies]
serialport = "4.7.0"
pyo3 = { version = "0.23.4", features = ["anyhow", "multiple-pymethods", "extension-module", "abi3-py37"] }
anyhow = "1.0.95"