[package]
name = "roboclaw_python"
version = "0.2.7"
edition = "2021"

[lib]
name = "roboclaw_python"
crate-type = ["cdylib"]

[dependencies]
serialport = "4.7.0"
thiserror = "2.0.11"
pyo3 = { version = "0.23.4", features = ["anyhow", "multiple-pymethods", "extension-module"] }
anyhow = "1.0.95"