name: Build on aarch64 and upload to pypi

on:
  push:
    paths:
      - "Cargo.toml"

jobs:
  check_version:
    runs-on: ubuntu-24.04-arm
    outputs:
      version_changed: ${{ steps.version_check.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check if the version changed
        id: version_check
        run: |
          if git diff HEAD^ HEAD -- Cargo.toml | grep -E '^\+version\s*=\s*".+"$'; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi
          echo "changed=${{ env.changed }}" >> $GITHUB_OUTPUT
  
  build:
    needs: check_version
    if: needs.check_version.outputs.version_changed == 'true'
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install maturin twine

      - name: Build
        run: |
          maturin build --release
      
      - name: Upload to pypi
        run: |
          python3 -m twine upload "./target/wheels/*" -p ${{ secrets.PYPI_TOKEN }}

